Exception at line 1 of t156_ExceptionRaise_test: just a test
  called from Exception.raise at line 1 of t156_ExceptionRaise_test
  called from execution environment
   1: Exception.raise "just a test"
   2: 
